# Site settings
title: "Antonio Trento Resume"
description: "A resume of a computer scence and art fanathic."
baseurl: "/jekyllresume.github.io" # the subpath of your site, e.g. /blog
url: "https://antcv.github.io/antcv/antcv.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Antonio Trento"
resume_title:                   "Web marketer, master and grow haker."
resume_contact_email:
  "lantoniotrento83@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_website_url:           "http://antfolio.guthub.io"
  resume_facebook_url:          "https://facebook.com/officialtrento"
  resume_linkedin_url:          "https://www.linkedin.com/in/antoniotrento"
  resume_instagram_url:         "https://instagram.com/officialtrento"
  resume_pinterest_url:         "https://pinterest.com/antoniotrento"
  resume_github_url:            "https://github.com/antoniotrento"
  resume_twitter_url:           "http://twitter.com/officialtrento"


# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
